// <auto-generated />
namespace AracKiralamaOtomasyonu3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AracResimEkleme : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AracResimEkleme));
        
        string IMigrationMetadata.Id
        {
            get { return "202411031056016_AracResimEkleme"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
